name: json-server
on:
  schedule:
    - cron: '*/2 * * * *'
  push:

jobs:
  build:
    name: merge request simulation
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Docker image simulator
        run: |
         echo "TARGET_ENVIRONMENT=prod" >> $GITHUB_ENV
         echo "PACKAGE_VERSION=1.2.2" >> $GITHUB_ENV
         echo "GITHUB_SHA_SHORT=ce45cv4" >> $GITHUB_ENV
         echo "REPOSITORY_NAME=${{github.repository}}" >> $GITHUB_ENV
 
      - name: Run e2e tests from separate repo
        id: moto-api
        continue-on-error: true
        uses: convictional/trigger-workflow-and-wait@v1.6.4 
        with:
          owner: Karel-Danes
          repo: cypress-repo
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          wait_interval: 10
          workflow_file_name: main.yml
          ref: master
          client_payload: '{"test_feature_branch_version":"v${{ env.PACKAGE_VERSION }}-${{ env.TARGET_ENVIRONMENT }}-${{ env.GITHUB_SHA_SHORT }}",
                            "service_name":"${{ env.REPOSITORY_NAME }}",
                            "test_case":"TC_001_e2e_alza",
                            "randomizer_active":"true",
                            "products_amount":"20"}'
        
      - name: E2E tests Success
        if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
      
        run: |
          echo "result is... ${{ steps.moto-api.outputs.conclusion }}"
          echo "local step e2e calling outcome: ${{toJSON(steps.moto-api.outcome)}}"
          echo "Detailed logs of Cypress run as a clue here ${{steps.moto-api.outputs.workflow_url}}"
          echo "## :white_check_mark: All E2E tests passed! :white_check_mark: log here ${{steps.moto-api.outputs.workflow_url}}"  >> $GITHUB_STEP_SUMMARY

      - name: E2E tests Failure debug
        if: (steps.moto-api.outputs.conclusion != 'success')
        run: |
          echo "result is... ${{ steps.moto-api.outputs.conclusion }}"      
          echo "local step e2e calling outcome: ${{toJSON(steps.moto-api.outcome)}}"
          echo "remote repository output conclusion: ${{toJSON(steps.moto-api.outputs)}}"
          echo "Detailed logs of Cypress run as a clue likely here (proper inputs required): ${{steps.moto-api.outputs.workflow_url}}"
          echo "## Some ❌ E2E tests failed! ❌ debug here ${{steps.moto-api.outputs.workflow_url}}"  >> $GITHUB_STEP_SUMMARY
          exit 1 

