name: json-server
on:
  push:

jobs:
  build:
    name: merge request simulation
    runs-on: ubuntu-latest
    steps:
 
      - name: run e2e tests from separate repo.
        id: moto-api
        continue-on-error: true
        uses: convictional/trigger-workflow-and-wait@v1.6.4 
        with:
          owner: Karel-Danes
          repo: cypress-repo
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          wait_interval: 10
          workflow_file_name: main.yml
          ref: master
          client_payload: '{"test_feature_db_name":"helelelele","test_case":"Kaufland"}'
        
      - name: E2E tests Success
        if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
        run: |
          echo "result is... ${{ steps.moto-api.outputs.conclusion }}"
          echo "Detailed logs of Cypress run as a clue here ${{steps.moto-api.outputs.workflow_url}}"
          echo "ref is ${{github.ref}}"
          echo "### :white_check_mark: All E2E tests passed! :white_check_mark: log here ${{steps.moto-api.outputs.workflow_url}} "  >> $GITHUB_STEP_SUMMARY

      - name: E2E tests Failure debug
        if: (steps.moto-api.outputs.conclusion != 'success')
        run: |
          echo "result is... ${{ steps.moto-api.outputs.conclusion }}"
          echo "local reporitory "Cypress call" outcome: ${{toJSON(steps.moto-api.outcome)}}"
          echo "remote repository output conclusion: ${{toJSON(steps.moto-api.outputs)}}"
          echo "Detailed logs of Cypress run as a clue likely here (proper inputs required): ${{steps.moto-api.outputs.workflow_url}}"
          echo "ref is ${{github.ref}}"
          echo "### Some :X: E2E tests failed! :X: debug here ${{steps.moto-api.outputs.workflow_url}}"  >> $GITHUB_STEP_SUMMARY
          exit 1 

