name: json-server
on:
  push:

jobs:
  build:
    name: merge request simulation
    runs-on: ubuntu-latest
    steps:
      #  - name: backend deploy
      #    run: |
      #      echo "simulation of backend building..."
      #      sleep 1s
      - name: run e2e tests from separate repo
        id: moto-api
        uses: convictional/trigger-workflow-and-wait@v1.6.4
        with:
          owner: Karel-Danes
          repo: cypress-repo
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          wait_interval: 10
          workflow_file_name: main.yml
          ref: master
          client_payload: '{"tags":"true", "moon":"full","environment":"alza"}'

        if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
        run: |
          echo "### All Cypress tests passed! :rocket:"
      - name: conclusion
        if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
        run: |
          echo "result is... ${{ steps.moto-api.outputs.conclusion }}"
          echo "${{ steps.moto-api.outputs.url_output }}" 

          echo "### All Cypress tests passed! :rocket: ${{ steps.moto-api.outputs }}"  >> $GITHUB_STEP_SUMMARY
          
