name: json-server
on:
  push:
  
jobs:
  build:
    name: backend deploy
    runs-on: ubuntu-latest
    steps:
      - name: backend deploy
        run: |
          echo "simulation of backend building..."
          sleep 5s
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: Karel-Danes
          repo: cypress-repo
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          wait_interval: 6
          workflow_file_name: main.yml
          ref: master
      - name: conclusion
        run: |
          echo "result is..."
          sleep 5s