name: json-server
on:
  push:

jobs:
  build:
    name: merge request simulation
    runs-on: ubuntu-latest
    steps:
      - name: backend deploy
        run: |
          echo "simulation of backend building.."
          sleep 1s
      - name: run e2e tests from separate repo
        id: moto-api
        uses: convictional/trigger-workflow-and-wait@v1.6.4
        with:
          owner: Karel-Danes
          repo: cypress-repo
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          wait_interval: 10
          workflow_file_name: main.yml
          ref: master
          client_payload: '{"tags":"true","environment":"alza","test-case":"alza"}'
   
      #  if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
      #  run: |
          
      - name: conclusion
    
        if: ${{ steps.moto-api.outputs.conclusion == 'success'}}
        run: |
          echo "Detailed logs of Cypress run as a clue here ${{steps.moto-api.outputs.workflow_url}}"
          echo "ref is ${{github.ref}}"

          echo "result is... ${{ steps.moto-api.outputs.conclusion }}"

          echo "### All Cypress tests passed! :rocket:" 

          echo "### All Cypress tests passed! :rocket: "  >> $GITHUB_STEP_SUMMARY
          
