name: json-server
on:
  push:
  
jobs:
  build:
    name: backend deploy
    runs-on: ubuntu-latest
    steps:
      - name: backend deploy
        run: |
          echo "simulation of backend building..."
          sleep 5s
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: Karel-Danes
          repo: cypress-api
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: main.yml
      - name: conclusion
        run: |
          echo "result is..."
          sleep 5s